name: uber_bagare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  mapbox_maps_flutter: ^2.6.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  provider: ^6.1.2
  supabase_flutter: ^2.8.3
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  google_maps_flutter: ^2.10.1







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_sign_in: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/user1.jpg
    - .env
    - assets/images/

