// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtTIZmOHqVfEY6BMMWNA-6fGbV0FOkTOM',
    appId: '1:421848232454:web:809b048148952de0818987',
    messagingSenderId: '421848232454',
    projectId: 'uber-bagarre-b7291',
    authDomain: 'uber-bagarre-b7291.firebaseapp.com',
    storageBucket: 'uber-bagarre-b7291.firebasestorage.app',
    measurementId: 'G-878BXLDT5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7qsdGunZV3RtL8sVlFPIk_Y1wv_Fdc6w',
    appId: '1:421848232454:android:d855244699fc5d9b818987',
    messagingSenderId: '421848232454',
    projectId: 'uber-bagarre-b7291',
    storageBucket: 'uber-bagarre-b7291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXx0KiNzlp-CGQm1vyJvFo4pt0CiqfLC8',
    appId: '1:421848232454:ios:667c915434d97bb7818987',
    messagingSenderId: '421848232454',
    projectId: 'uber-bagarre-b7291',
    storageBucket: 'uber-bagarre-b7291.firebasestorage.app',
    iosBundleId: 'com.example.uberBagarre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXx0KiNzlp-CGQm1vyJvFo4pt0CiqfLC8',
    appId: '1:421848232454:ios:667c915434d97bb7818987',
    messagingSenderId: '421848232454',
    projectId: 'uber-bagarre-b7291',
    storageBucket: 'uber-bagarre-b7291.firebasestorage.app',
    iosBundleId: 'com.example.uberBagarre',
  );
}
